/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/api/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * User login
     * @description Authenticate with username and password. Returns a session token and sets an HttpOnly cookie.
     */
    post: operations["loginUser"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * User logout
     * @description Logout and invalidate the current session. Clears the session cookie.
     */
    post: operations["logoutUser"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/profile": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user profile
     * @description Get the profile information of the currently authenticated user.
     */
    get: operations["getUserProfile"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/profile/change-password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Change password
     * @description Change the password for the currently authenticated user. Requires current password verification.
     */
    post: operations["changeUserPassword"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/forums": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all forums
     * @description Get a list of all available forums.
     */
    get: operations["listForums"]
    put?: never
    /**
     * Create new forum
     * @description Create a new forum with a unique slug, title, description, and category.
     */
    post: operations["createForum"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/forums/{slug}/posts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List forum posts
     * @description Get paginated posts for a specific forum, sorted by creation date (newest first).
     */
    get: operations["listForumPosts"]
    put?: never
    /**
     * Create new post
     * @description Create a new post in a forum. The post will be assigned the next sequential number.
     */
    post: operations["createForumPost"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/forums/{slug}/posts/{post_number}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get single post
     * @description Get a specific post by its sequential number within a forum.
     */
    get: operations["getForumPost"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/forums/{slug}/posts/{post_number}/comments": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List post comments
     * @description Get all comments for a specific post, sorted by creation date (newest first).
     */
    get: operations["listPostComments"]
    put?: never
    /**
     * Create new comment
     * @description Create a new comment on a specific post.
     */
    post: operations["createPostComment"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List all users
     * @description Get a list of all users in the system (excluding password information).
     */
    get: operations["listUsers"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Health check endpoint
     */
    get: operations["health_check__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export type components = {
  schemas: {
    /**
     * ChangePasswordRequest
     * @description Request to change user password.
     * @example {
     *       "currentPassword": "oldpass123",
     *       "newPassword": "newpass456"
     *     }
     */
    ChangePasswordRequest: {
      /**
       * Currentpassword
       * @description Current password
       */
      currentPassword: string
      /**
       * Newpassword
       * @description New password
       */
      newPassword: string
    }
    /**
     * Comment
     * @description Comment information.
     */
    Comment: {
      /**
       * Id
       * @description Unique comment identifier
       */
      id: string
      /**
       * Postid
       * @description ID of the post this comment belongs to
       */
      postId: string
      /**
       * Content
       * @description Comment content
       */
      content: string
      /**
       * Authorid
       * @description ID of the comment author
       */
      authorId: string
      /**
       * Createdat
       * Format: date-time
       * @description Comment creation timestamp
       */
      createdAt: string
      /**
       * Updatedat
       * @description Comment last update timestamp
       */
      updatedAt?: string | null
    }
    /**
     * CreateCommentRequest
     * @description Request to create a new comment.
     * @example {
     *       "content": "Great post! Thanks for sharing."
     *     }
     */
    CreateCommentRequest: {
      /**
       * Content
       * @description Comment content
       */
      content: string
    }
    /**
     * CreateForumRequest
     * @description Request to create a new forum.
     * @example {
     *       "category": "Technology",
     *       "description": "Discuss Python programming topics",
     *       "slug": "python-discussion",
     *       "title": "Python Discussion"
     *     }
     */
    CreateForumRequest: {
      /**
       * Title
       * @description Forum title
       */
      title: string
      /**
       * Slug
       * @description URL-friendly unique identifier (lowercase letters, numbers, hyphens)
       */
      slug: string
      /**
       * Description
       * @description Forum description
       */
      description: string
      /**
       * Category
       * @description Forum category (Technology, Science, or Art)
       * @enum {string}
       */
      category: "Technology" | "Science" | "Art"
    }
    /**
     * CreatePostRequest
     * @description Request to create a new post.
     * @example {
     *       "content": "FastAPI is a modern web framework...",
     *       "tags": [
     *         "python",
     *         "fastapi",
     *         "tutorial"
     *       ],
     *       "title": "Getting started with FastAPI"
     *     }
     */
    CreatePostRequest: {
      /**
       * Title
       * @description Post title
       */
      title: string
      /**
       * Content
       * @description Post content
       */
      content: string
      /**
       * Tags
       * @description List of tags for the post
       */
      tags?: string[]
    }
    /**
     * ErrorResponse
     * @description Standard error response format.
     * @example {
     *       "message": "Invalid credentials",
     *       "type": "authentication_error"
     *     }
     * @example {
     *       "message": "Not authenticated",
     *       "type": "unauthorized"
     *     }
     * @example {
     *       "message": "Forum not found",
     *       "type": "not_found"
     *     }
     * @example {
     *       "message": "Post not found",
     *       "type": "not_found"
     *     }
     * @example {
     *       "message": "Access denied",
     *       "type": "access_denied"
     *     }
     */
    ErrorResponse: {
      /**
       * Message
       * @description Human-readable error message
       */
      message: string
      /**
       * Type
       * @description Machine-readable error type
       */
      type: string
    }
    /**
     * Forum
     * @description Forum information.
     */
    Forum: {
      /**
       * Id
       * @description Unique forum identifier
       */
      id: string
      /**
       * Slug
       * @description URL-friendly forum identifier
       */
      slug: string
      /**
       * Title
       * @description Forum title
       */
      title: string
      /**
       * Description
       * @description Forum description
       */
      description: string
      /**
       * Category
       * @description Forum category
       * @enum {string}
       */
      category: "Technology" | "Science" | "Art"
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * LoginRequest
     * @description Request to authenticate a user.
     * @example {
     *       "password": "admin123",
     *       "username": "admin"
     *     }
     * @example {
     *       "password": "securepassword",
     *       "username": "john_doe"
     *     }
     */
    LoginRequest: {
      /**
       * Username
       * @description Username
       */
      username: string
      /**
       * Password
       * @description Password
       */
      password: string
    }
    /**
     * LoginResponse
     * @description Response after successful authentication.
     * @example {
     *       "authToken": "abc123def456"
     *     }
     */
    LoginResponse: {
      /**
       * Authtoken
       * @description Authentication token
       */
      authToken: string
    }
    /**
     * MessageResponse
     * @description Generic message response.
     */
    MessageResponse: {
      /**
       * Message
       * @description Response message
       */
      message: string
    }
    /** PaginatedResponse[Post] */
    PaginatedResponse_Post_: {
      /**
       * Items
       * @description List of items in current page
       */
      items: components["schemas"]["Post"][]
      /**
       * Total Count
       * @description Total number of items across all pages
       */
      total_count: number
      /**
       * Page
       * @description Current page number (1-indexed)
       */
      page: number
      /**
       * Page Size
       * @description Number of items per page
       */
      page_size: number
      /**
       * Total Pages
       * @description Total number of pages
       */
      total_pages: number
    }
    /**
     * Post
     * @description Post information.
     */
    Post: {
      /**
       * Id
       * @description Unique post identifier
       */
      id: string
      /**
       * Forumid
       * @description ID of the forum this post belongs to
       */
      forumId: string
      /**
       * Number
       * @description Sequential post number within the forum
       */
      number: number
      /**
       * Title
       * @description Post title
       */
      title: string
      /**
       * Content
       * @description Post content
       */
      content: string
      /**
       * Tags
       * @description List of tags associated with the post
       */
      tags: string[]
      /**
       * Authorid
       * @description ID of the post author
       */
      authorId: string
      /**
       * Createdat
       * Format: date-time
       * @description Post creation timestamp
       */
      createdAt: string
      /**
       * Updatedat
       * @description Post last update timestamp
       */
      updatedAt?: string | null
    }
    /**
     * User
     * @description User profile information.
     */
    User: {
      /**
       * Id
       * @description Unique user identifier
       */
      id: string
      /**
       * Username
       * @description Username
       */
      username: string
      /**
       * Role
       * @description User role (admin or user)
       * @enum {string}
       */
      role: "admin" | "user"
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  loginUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["LoginResponse"]
        }
      }
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  logoutUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logout successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  getUserProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User profile retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["User"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  changeUserPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"]
      }
    }
    responses: {
      /** @description Password changed successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["MessageResponse"]
        }
      }
      /** @description Current password is incorrect */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listForums: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of forums */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forum"][]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  createForum: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateForumRequest"]
      }
    }
    responses: {
      /** @description Forum created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Forum"]
        }
      }
      /** @description Forum with this slug already exists */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listForumPosts: {
    parameters: {
      query?: {
        /** @description Page number (1-indexed) */
        page?: number
        /** @description Number of items per page */
        page_size?: number
      }
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Paginated list of posts */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["PaginatedResponse_Post_"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Forum not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  createForumPost: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePostRequest"]
      }
    }
    responses: {
      /** @description Post created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Post"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Forum not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  getForumPost: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
        post_number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Post retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Post"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Forum or post not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listPostComments: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
        post_number: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of comments */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Comment"][]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Forum or post not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  createPostComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        slug: string
        post_number: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"]
      }
    }
    responses: {
      /** @description Comment created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["Comment"]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Forum or post not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  listUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of users */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["User"][]
        }
      }
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["ErrorResponse"]
        }
      }
    }
  }
  health_check__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            [key: string]: string
          }
        }
      }
    }
  }
}
